In [1]:
import sys
sys.path.append( '/Users/sultandaniels/Documents/ENGN1000/mealmaker_real/src/autochef/data' )
import node as nd
import Mutation as mt
import initial_popul as pop
import numpy as np
import fitness_eval as fit


In [2]:
import ingredients_list as all_ing
all_ing = all_ing.ingredients
import actions_list
cooking_verbs = actions_list.cooking_verbs
heat = actions_list.heat
cool = actions_list.cool
prepare = actions_list.prepare

In [3]:
ing_ing_mat = np.loadtxt('/Users/sultandaniels/Documents/ENGN1000/adj_matrices/ingredients_to_ingredients_thresholded_matrix.csv', delimiter=",", dtype=float)

act_ing_mat = np.loadtxt('/Users/sultandaniels/Documents/ENGN1000/adj_matrices/actions_to_ingredients_thresholded_matrix.csv', delimiter=",", dtype=float)

actgrp_ing_mat = np.loadtxt('/Users/sultandaniels/Documents/ENGN1000/adj_matrices/action_groups_to_ingredients_heat_cool_prepare_thresholded_matrix.csv', delimiter=",", dtype=float)

prep_inds = np.loadtxt('/Users/sultandaniels/Documents/ENGN1000/actions_and_ingredients_lists/prepare_actions_indices.csv', delimiter=",", dtype=float)
prep_inds = prep_inds.astype(int)
prep_inds = prep_inds.tolist()

heat_inds = np.loadtxt('/Users/sultandaniels/Documents/ENGN1000/actions_and_ingredients_lists/heat_actions_indices.csv', delimiter=",", dtype=float)

heat_inds = heat_inds.astype(int)
heat_inds = heat_inds.tolist()

# Test Tree Creation

In [4]:
ings = all_ing[10:15] # user inputted ingredients

ing_inds = pop.ing_indices(ings, all_ing) # ingredient indices

test_tree = pop.initialize_tree(1,ings,all_ing,ing_inds,act_ing_mat,prep_inds,heat_inds,actgrp_ing_mat,0.35,cooking_verbs,0.65)

user inputted ings:
 ['wensleydale', 'coconut aminos', 'accompaniment', 'liquid', 'field peas']
ingredient indices:
 [10, 11, 12, 13, 14]

initial trees:
tree 0 root: wensleydale
tree 1 root: coconut aminos
tree 2 root: accompaniment
tree 3 root: liquid
tree 4 root: field peas
need_prep: [0, 0, 1, 1, 0]

prepare actions added
tree 0 root: wensleydale
tree 1 root: coconut aminos
tree 2 root: garnish
tree 3 root: serve
tree 4 root: field peas
need_heat: [1, 1, 0, 0, 1]

heat actions added
tree 0 root: burn
tree 1 root: braise
tree 2 root: garnish
tree 3 root: serve
tree 4 root: sauté

merge trees with the same action root
tree 0 root: burn
tree 1 root: braise
tree 2 root: garnish
tree 3 root: serve
tree 4 root: sauté

final valid tree
root: mix
root's children:
child 0 : burn
child 1 : braise
child 2 : garnish
child 3 : serve
child 4 : sauté


# Mutating the Tree

In [5]:
# initialize population
current_pop = pop.init_pop(75, ings, all_ing, ing_inds, act_ing_mat, prep_inds, heat_inds, actgrp_ing_mat, 0.35, cooking_verbs, 0.65)


# gens = 35
# k = np.random.randint(3)
# if k == 0: # mutate mix node
# elif k == 1: # mutate action node
# elif k == 2: # mutate ingredient node

[<node.Node object at 0x117672260>, <node.Node object at 0x1176722c0>, <node.Node object at 0x1176721a0>, <node.Node object at 0x117672200>, <node.Node object at 0x117672320>]


In [34]:
node1 = nd.Node("action", 3)
node2 = nd.Node("action", 2)
node3 = nd.Node("mix", 3)
node4 = nd.Node("ing", 4)
node5 = nd.Node("ing", 12)
node6 = nd.Node("ing", 317)


nd.Node.insert_child(node3,[node1, node2])
tree1 = nd.Tree(node3)
nd.Node.insert_child(node2,[node5])
tree2 = nd.Tree(node2)
nd.Node.insert_child(node1,[node6,node4])
tree3 = nd.Tree(node1)
tree4 = nd.Tree(node4)

# node1.children.append(node.Node(3)) #figure out index
# print(node1.children[0].index)

In [35]:
trees = nd.Tree.check_same_act([tree2,tree1,tree3,tree4])
print(trees)

[<node.Tree object at 0x121757f70>, <node.Tree object at 0x121780700>, <node.Tree object at 0x121754ac0>, <node.Tree object at 0x1217571f0>]


In [36]:
val_tree = nd.Tree.make_valid(trees)
print(val_tree.root.children)

[<node.Node object at 0x1217577f0>, <node.Node object at 0x121757970>, <node.Node object at 0x121754190>, <node.Node object at 0x121754730>]


In [5]:
print(len(val_tree.root.children))
print(val_tree.root.children[0].category)
print(mt.act_mut(val_tree.root, None, cooking_verbs))


3
action
adding action 106
True


In [6]:
print(val_tree.root.children[2].children[0].children[0].children[1].category)

IndexError: list index out of range

In [7]:
vcop = val_tree.copy()

In [8]:
print(len(vcop.root.children))
print(len(val_tree.root.children))

3
3


action
ing


# Fitness Eval

In [11]:
print(fit.num_acts(test_tree.root,0,15))

1


In [21]:
first_child = test_tree.root.children[0]
print(first_child.category)
print(first_child.children[0].category)
print(first_child.children[0].index)

action
ing
11


[<node.Node object at 0x109b271c0>, <node.Node object at 0x109b26b90>, <node.Node object at 0x109b270d0>, <node.Node object at 0x109b24e20>, <node.Node object at 0x109b272e0>]


deleting action 2


True

None


In [5]:
node1 = nd.Node("action", 2)
node2 = nd.Node("action", 2)
node3 = nd.Node("action", 2)
node4 = nd.Node("ing", 13)
node5 = nd.Node("ing", 67)
node6 = nd.Node("ing", 109)

nd.Node.insert_child(node3,[node4, node5,node6])
nd.Node.insert_child(node2,[node3])
nd.Node.insert_child(node1,[node2])
tree1 = nd.Tree(node1)

print(fit.num_dup_acts(node1,0,80,[]))

None


In [11]:
b_h = pop.need_heat_act(ings,all_ing,actgrp_ing_mat,0.65)
b_p = pop.need_prep_act(ings,all_ing,actgrp_ing_mat,0.35)
s_h = fit.s_heat(b_h, ings, actgrp_ing_mat, 0.65, 0.1)
s_p = fit.s_heat(b_p, ings, actgrp_ing_mat, 0.35, 0.1)
print("here")
s_a = fit.s_act(test_tree, ing_inds)
print(fit.s_ing(s_h, s_p, s_a))

here
[1.0, 1.0, 1.0, 1.0, 1.0]


In [12]:
first_act = test_tree.root.children[0]

In [20]:
print(fit.valid_act(node3, node3.index, act_ing_mat, []))

[1, 1, 0]


In [22]:
first_act.children[0].index
node3.children

[<node.Node at 0x12061e8f0>, <node.Node at 0x12061feb0>]

In [18]:
act_ing_mat[first_act.index, first_act.children[0].index]

0.0

In [15]:
act_ing_mat.nonzero()

(array([  0,   0,   0, ..., 109, 109, 109]),
 array([  13,   56,   67, ..., 6704, 6709, 6713]))

In [18]:
act_ing_mat[2,109]

0.0

In [37]:
s_i = [None]*len(node3.children)
s_i = fit.s_mix_tuples(node3, s_i)

In [38]:
s_i

[[317, 4], [12]]

In [39]:
tups = fit.tuple_pairs(s_i)

In [40]:
tups[0]

(317, 12)

In [42]:
fit.s_mix(tups,ing_ing_mat)

1.0

In [11]:
ing_ing_mat.nonzero()

(array([  12,   12,   12, ..., 6713, 6713, 6713]),
 array([  12,  317,  979, ..., 5423, 6219, 6713]))

In [33]:
ing_ing_mat[12,317]

2.0